# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: amrdeveloper.gitql
PackageVersion: 0.37.0
InstallerType: portable
Commands:
  - gitql
Installers:
  - Architecture: x86
    InstallerUrl: https://github.com/AmrDeveloper/GQL/releases/download/0.37.0/gql-x86-windows.exe
    InstallerSha256: 5fc9d6a055ef6f21cec8e41f669eae5da998b8f849e19854201a16949c507c51
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
        - PackageIdentifier: Microsoft.UI.Xaml.2.8
  - Architecture: x64
    InstallerUrl: https://github.com/AmrDeveloper/GQL/releases/download/0.37.0/gql-x86_64-windows.exe
    InstallerSha256: 79b627b588751fe3b344ecb5466bd92db30620847f02755e40b5a394b62e2911
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
        - PackageIdentifier: Microsoft.UI.Xaml.2.8
ManifestType: installer
ManifestVersion: 1.5.0
